---
- name: Деплой Redmine с PostgreSQL
  hosts: webservers
  become: yes
  vars_files:
    - group_vars/webservers/vars.yml
    - group_vars/webservers/vault.yml

  tasks:
    - name: Удалить старый контейнер (если есть)
      docker_container:
        name: redmine
        state: absent

    - name: Запустить Redmine с PostgreSQL
      docker_container:
        name: redmine
        image: redmine:latest
        state: started
        restart_policy: always
        ports:
          - "{{ redmine_port }}:3000"
        env:
          REDMINE_DB_POSTGRES: "{{ redmine_db_host }}"
          REDMINE_DB_PORT: "{{ redmine_db_port }}"
          REDMINE_DB_USERNAME: "{{ redmine_db_username }}"
          REDMINE_DB_PASSWORD: "{{ redmine_db_password }}"
          REDMINE_DB_DATABASE: "{{ redmine_db_database }}"