redmine_port: 3000
redmine_db_host: rc1b-6l6eqv7ucphvrdcq.mdb.yandexcloud.net
redmine_db_port: "6432"
redmine_db_username: app_user
redmine_db_database: my-db
redmine_db_password: "{{ vault_redmine_db_password }}"